version: '3.6'

services:
  minecraft:
    build: .
    tty: true
    volumes:
      - ./data:/data
    environment:
      - EULA=TRUE
      - TYPE=FORGE
      - WHITE_LIST=TRUE
    restart: always
    ports:
        - "25565:25565"